---
title: "eda"
output: html_document
date: "2024-08-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Loading libraries

```{r echo = FALSE}
library(tidyverse)
library(lubridate)
```

## Including Plots

Loading data

```{r  echo=FALSE , results='hide'}
reservations <- read_csv("data_2024_/reservations.csv", show_col_types = FALSE)
room_reservations <- read_csv("data_2024_/room_reservations.csv", show_col_types = FALSE)
room_names <- read_csv("data_2024_/room_name.csv", show_col_types = FALSE)
customers_data <- read_csv("data_2024_/customers_data.csv", show_col_types = FALSE)
customers_reservations <- read_csv("data_2024_/customers_reservations.csv", show_col_types = FALSE)
```

Occupation rate by room

```{r echo = FALSE}
room_reservations_confirmed <- room_reservations %>% 
  left_join(reservations, by = c("id_reserva"="id")) %>% 
  filter(status == "Confirmed") %>% 
  mutate(start_date = lubridate::dmy(start_date),
         end_date = lubridate::dmy(end_date)) %>% 
  mutate(diff_days =  as.integer(end_date - start_date)) %>% 
  left_join(room_names, by = c("id_zak_room"="id")) %>% 
  filter(id_name_type != 'TBC')  %>% ## Borrar cuando actualice
  mutate(price_by_day = total_price/diff_days)  %>% 
  group_by(id_name_type) %>%
  mutate(
    mean_price = mean(price_by_day),
    sd_price = sd(price_by_day),
    Q1 = quantile(price_by_day, 0.25),
    Q3 = quantile(price_by_day, 0.75),
    median = quantile(price_by_day, 0.5),
    z_score = (price_by_day - mean_price) / sd_price,
    rango = 0.25 * quantile(price_by_day, 0.5)
  )  %>% 
   mutate( # if value 25% of deviation from median, adjust median (20% maximum disco)
    price_by_day = ifelse(
      abs(price_by_day) - median > rango,
      median,
      price_by_day
    ))
  


occupation_rate_by_room <- room_reservations_confirmed %>% 
  mutate(total_days = as.integer(max(start_date) - min(start_date) )) %>% 
  group_by(total_days,id_name_type) %>% 
  summarise(days = sum(diff_days),
            nrooms = n_distinct(id_zak_room),
            total_price = sum(total_price),
            mediana = median(price_by_day),
            media = mean(price_by_day)
            ) %>% 
  mutate(avg_price = total_price/days,
         occupation_rate = days/(total_days*nrooms)) %>% 
  mutate(RevPar = occupation_rate*avg_price)

```
 Avg price vs occupation rate by room
```{r}

# Calcula la pendiente ajustada
max_avg_price <- max(occupation_rate_by_room$media)
slope <- 1 / max_avg_price  # Si occupation_rate varía de 0 a 1

# Genera el gráfico con la línea ajustada desde el origen
ggplot(occupation_rate_by_room, aes(media, occupation_rate, color = as.factor(id_name_type))) +  
  geom_abline(slope = slope, intercept = 0, linetype = "dashed", color = "black") +  # Línea ajustada desde (0, 0)
  geom_point(size = 3) +  # Luego, añade los puntos
   geom_text(aes(label = paste0("RevPar ", round(RevPar, 0)," COP")), vjust = -1, size = 2.5) + 
  labs(x = "Precio promedio (COP)", y = "Proporción ocupada", color = "Tipo de habitación") + 
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_color_discrete(name = "Tipo de habitación") +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent)+
scale_x_continuous(limits = c(0, 150000))


geom_text(aes(label = paste0("$", format(round(RevPAR, 2), big.mark = "."))), 
            vjust = -1, size = 4)

```

Occupation rate by date 
```{r}
# Expandimos las reservas a nivel diario
reservas_diarias <- room_reservations_confirmed %>%
  select(id_name_type,id_zak_room,start_date,end_date,diff_days) %>% 
  uncount(diff_days , .id = "dia") %>%
  mutate(fecha = start_date + days(dia - 1)) %>% 
  filter(fecha <= '2024-07-31')

# Calculamos la capacidad total por tipo de habitación (asumimos que es constante)
capacidad_total <- reservas_diarias %>%
  group_by(id_name_type) %>% 
  summarise(capacidad_total = n_distinct(id_zak_room))

capacidad_total_general <- sum(capacidad_total$capacidad_total)


occupation_rate <- reservas_diarias %>%
  left_join(capacidad_total, by = "id_name_type") %>%
  group_by(fecha) %>%
    summarize(num_reservas = n()) %>% 
  mutate(ocupacion_porcentaje = num_reservas / capacidad_total_general )


ggplot(occupation_rate, aes(fecha,ocupacion_porcentaje)) +
  geom_line() +
  theme_minimal() + 
  scale_y_continuous(limits = c(0, 1), labels = scales::percent)


```
Occupation rate by day and room_type
```{r}

# Contamos el número de reservas por día y tipo de habitación y calculamos el porcentaje de ocupación
ocupacion_por_dia <- reservas_diarias %>%
  group_by(fecha, id_name_type) %>%
  summarize(num_reservas = n()) %>%
  left_join(capacidad_total, by = "id_name_type") %>%
  mutate(ocupacion_porcentaje = num_reservas / capacidad_total )



 ggplot(ocupacion_por_dia %>% 
          filter(id_name_type != 'TBC')
          , aes(x = fecha, y = ocupacion_porcentaje,color = id_name_type)) +
  theme_minimal() + 
  scale_y_continuous(limits = c(0, 1), labels = scales::percent)+
     geom_line() +
   
     facet_wrap(~ id_name_type, ncol = 3) +  # Ajusta el número de columnas si lo deseas
   labs(
         x = "Fecha",
         y = "Porcentaje de Ocupación",
         title = "Evolución de la Ocupación por Tipo de Habitación"
      )


```
RevPar by date
```{r}
RevPar <- room_reservations_confirmed %>% 
  uncount(diff_days , .id = "dia") %>%
  mutate(fecha = start_date + days(dia - 1)) %>% 
  filter(fecha <= '2024-07-31') %>% 
  group_by(fecha) %>% 
  summarise(n_rooms = n(),
            total_revenue = sum(price_by_day)) %>% 
  mutate(occupation = n_rooms/capacidad_total_general,
    adr_day = total_revenue/n_rooms) %>% 
  mutate(RevPar_day = adr_day * occupation)
  
  
  
  ggplot(RevPar, aes(fecha,RevPar_day)) +
  geom_line() +
  theme_minimal()


```



RevPar by date and room_type
```{r}

RevPar_room_type <- room_reservations_confirmed %>% 
  uncount(diff_days , .id = "dia") %>%
  mutate(fecha = start_date + days(dia - 1)) %>% 
  filter(fecha <= '2024-07-31') %>% 
  group_by(fecha,id_name_type) %>% 
  summarise(n_rooms = n(),
            total_revenue = sum(price_by_day)) %>% 
  left_join(capacidad_total, by = "id_name_type")%>% 
  mutate(occupation = n_rooms/capacidad_total,
    adr_day = total_revenue/n_rooms) %>% 
  mutate(RevPar_day = adr_day * occupation)



 ggplot(RevPar_room_type  
                    , aes(x = fecha, y = RevPar_day,color = id_name_type)) +
        geom_line() +
    facet_wrap(~ id_name_type, ncol = 3) 




```



Stay duration by room type

```{r}
duration <- reservas_diarias %>% 
  group_by(id_zak_room,id_name_type,start_date) %>% 
  summarise(dias = max(dia))


ggplot(duration, aes(x=id_name_type,y=dias, fill = id_name_type))+
geom_boxplot()+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

```

Revenue proportion by room_type

```{r}

revenue_by_room_type <- room_reservations_confirmed %>% 
  group_by(id_name_type) %>% 
  summarise(room_revenue = sum( price_by_day*diff_days )) %>% 
  mutate(total_revenue = sum(room_revenue)) %>% 
  mutate(prop = room_revenue/total_revenue)


ggplot(revenue_by_room_type, aes(fct_reorder(id_name_type, -prop),prop))+
  geom_col()+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ 
  scale_y_continuous(limits = c(0, 1), labels = scales::percent) +  
   labs(
         x = "Date",
         y = "Proportion",
         title = "Revenue proportion by room_type"
      )



```





```{r}



```

